version: '3.8'

services:
  scorecard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scorecard-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - scorecard-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PATH=/app/data
      - REACT_APP_API_URL=${API_URL:-http://localhost:3000}
      - REACT_APP_APP_NAME=${APP_NAME:-LevelTen}

volumes:
  scorecard-data:
    # Persist data between container restarts